### ISSUE TITLE
Добавляем workflow

### ISSUE THREAD

**Issue by eroshenkoam** [itishniki/github-actions-java-cmd#5]
Для сборки
```
name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build"
        run: ./gradlew build
      - name: "Build Native Image"
        run: ./gradlew nativeImage
```

Для релиза
```
name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build"
        run: ./gradlew build
      - name: "Build Native Image"
        run: ./gradlew nativeImage
      - name: "Upload Native Image"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/graal/search-for-me
          asset_name: search-for-me
          asset_content_type: application/octet-stream
```
